### ISSUE TITLE
From Wav

### ISSUE THREAD

**Issue by OrhanALC** [slruslan/php-waveform2png#1]
Is it easy to change the code so it just creates png of wav files not mp3? If it is, which part, method, function should I change in order to achieve this goal?

**Comment by slruslan** [comment]
Greetings, @OrhanALC :)

There is a method Waveform2Png::process, which has the $wavList variable.
You can simply change the code to put files directly to this array, without calling Waveform2Png::generateWavFiles.

That's how you can achieve your goal :)
